In [1]:
from wav2aud import wav2aud

import numpy as np
import pandas as pd
import os
import sys

In [2]:

# sort out wd
script_directory = os.path.dirname(os.path.abspath(sys.argv[0]))
print("Current working directory:", os.getcwd())
#print("Script directory:", script_directory)

#os.chdir(script_directory)
#print("Now working directory is ", os.getcwd())

Current working directory: c:\Users\carol\OneDrive\Documents\UMaastricht\Audio2sem_project

In [3]:
# import cochba
df = pd.read_csv("cochba_py.csv", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,128
0,22.000000 + 6.488793i,22.000000 + 6.787004i,24.000000 + 6.817392i,22.000000 + 6.827376i,20.000000 + 6.832618i,19.000000 + 6.830657i,21.000000 + 6.825671i,19.000000 + 6.825753i,18.000000 + 6.819632i,18.000000 + 6.829132i,...,7.000000 + 6.594401i,7.000000 + 6.528693i,7.000000 + 6.445553i,7.000000 + 6.338455i,7.000000 + 6.200292i,7.000000 + 6.019685i,7.000000 + 5.780572i,7.000000 + 5.457179i,7.000000 + 5.006865i,7.000000 + 4.359530i
1,0.002923 + 1.000000i,0.003008 + 1.000000i,0.003096 + 1.000000i,0.003187 + 1.000000i,0.003280 + 1.000000i,0.003376 + 1.000000i,0.003475 + 1.000000i,0.003577 + 1.000000i,0.003681 + 1.000000i,0.003789 + 1.000000i,...,0.090574 + 1.000000i,0.093190 + 1.000000i,0.095871 + 1.000000i,0.098615 + 1.000000i,0.101421 + 1.000000i,0.104290 + 1.000000i,0.107231 + 1.000000i,0.110272 + 1.000000i,0.113478 + 1.000000i,0.116975 + 1.000000i
2,-0.001726 + -1.571705i,-0.001786 + -1.581004i,-0.001438 + -1.438691i,-0.001926 + -1.572814i,-0.002487 + -1.738847i,-0.002813 + -1.819619i,-0.002335 + -1.642932i,-0.003078 + -1.818260i,-0.003484 + -1.916427i,-0.003641 + -1.919417i,...,0.134416 + 2.744154i,0.158160 + 3.025813i,0.187063 + 3.347604i,0.214504 + 3.638147i,0.246196 + 3.955347i,0.275770 + 4.234792i,0.307478 + 4.517695i,0.340523 + 4.794193i,0.191940 + 3.448425i,0.203281 + 3.538696i
3,-0.002610 + -0.305291i,-0.002681 + -0.296031i,-0.002592 + -0.376753i,-0.002844 + -0.298659i,-0.003048 + -0.175452i,-0.003182 + -0.107966i,-0.003169 + -0.249072i,-0.003347 + -0.101592i,-0.003456 + -0.008072i,-0.003533 + 0.000374i,...,-0.027793 + 4.306743i,-0.013781 + 4.856525i,0.011130 + 5.585862i,0.038627 + 6.303750i,0.078224 + 7.183626i,0.119443 + 8.016723i,0.170204 + 8.935481i,0.229500 + 9.904481i,-0.127638 + 4.326547i,-0.124355 + 4.454945i
4,-0.001663 + 0.311611i,-0.001698 + 0.320780i,-0.001966 + 0.186066i,-0.001763 + 0.314716i,-0.001420 + 0.482702i,-0.001235 + 0.568036i,-0.001750 + 0.386445i,-0.001180 + 0.567695i,-0.000885 + 0.672004i,-0.000834 + 0.674356i,...,-0.259345 + 3.931675i,-0.276996 + 4.575552i,-0.294823 + 5.477592i,-0.307935 + 6.366814i,-0.317272 + 7.523691i,-0.319261 + 8.639756i,-0.313400 + 9.936303i,-0.297539 + 11.371554i,-0.331975 + 1.797245i,-0.336695 + 1.713404i

In [18]:
def convert_complex(complex_str):
    complex_str = complex_str.replace('i', 'j')
    complex_str = complex_str.replace(' ', '')
    complex_str = complex_str.replace('+-', '-')
    return complex_str

In [19]:
df_processed = df.applymap(convert_complex)
df_processed

,0,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,128
0,22.000000+6.488793j,22.000000+6.787004j,24.000000+6.817392j,22.000000+6.827376j,20.000000+6.832618j,19.000000+6.830657j,21.000000+6.825671j,19.000000+6.825753j,18.000000+6.819632j,18.000000+6.829132j,...,7.000000+6.594401j,7.000000+6.528693j,7.000000+6.445553j,7.000000+6.338455j,7.000000+6.200292j,7.000000+6.019685j,7.000000+5.780572j,7.000000+5.457179j,7.000000+5.006865j,7.000000+4.359530j
1,0.002923+1.000000j,0.003008+1.000000j,0.003096+1.000000j,0.003187+1.000000j,0.003280+1.000000j,0.003376+1.000000j,0.003475+1.000000j,0.003577+1.000000j,0.003681+1.000000j,0.003789+1.000000j,...,0.090574+1.000000j,0.093190+1.000000j,0.095871+1.000000j,0.098615+1.000000j,0.101421+1.000000j,0.104290+1.000000j,0.107231+1.000000j,0.110272+1.000000j,0.113478+1.000000j,0.116975+1.000000j
2,-0.001726-1.571705j,-0.001786-1.581004j,-0.001438-1.438691j,-0.001926-1.572814j,-0.002487-1.738847j,-0.002813-1.819619j,-0.002335-1.642932j,-0.003078-1.818260j,-0.003484-1.916427j,-0.003641-1.919417j,...,0.134416+2.744154j,0.158160+3.025813j,0.187063+3.347604j,0.214504+3.638147j,0.246196+3.955347j,0.275770+4.234792j,0.307478+4.517695j,0.340523+4.794193j,0.191940+3.448425j,0.203281+3.538696j
3,-0.002610-0.305291j,-0.002681-0.296031j,-0.002592-0.376753j,-0.002844-0.298659j,-0.003048-0.175452j,-0.003182-0.107966j,-0.003169-0.249072j,-0.003347-0.101592j,-0.003456-0.008072j,-0.003533+0.000374j,...,-0.027793+4.306743j,-0.013781+4.856525j,0.011130+5.585862j,0.038627+6.303750j,0.078224+7.183626j,0.119443+8.016723j,0.170204+8.935481j,0.229500+9.904481j,-0.127638+4.326547j,-0.124355+4.454945j
4,-0.001663+0.311611j,-0.001698+0.320780j,-0.001966+0.186066j,-0.001763+0.314716j,-0.001420+0.482702j,-0.001235+0.568036j,-0.001750+0.386445j,-0.001180+0.567695j,-0.000885+0.672004j,-0.000834+0.674356j,...,-0.259345+3.931675j,-0.276996+4.575552j,-0.294823+5.477592j,-0.307935+6.366814j,-0.317272+7.523691j,-0.319261+8.639756j,-0.313400+9.936303j,-0.297539+11.371554j,-0.331975+1.797245j,-0.336695+1.713404j
5,-0.000175+0.495021j,-0.000170+0.497987j,-0.000663+0.402775j,-0.000126+0.492352j,0.000540+0.583061j,0.000915+0.623251j,0.000179+0.534950j,0.001103+0.615381j,0.001571+0.648804j,0.001681+0.643441j,...,-0.229009+2.435007j,-0.254560+2.813034j,-0.291995+3.420835j,-0.324189+4.022018j,-0.366178+4.866777j,-0.400065+5.681188j,-0.436735+6.669584j,-0.472616+7.800641j,-0.009569-0.860833j,-0.004201-1.110936j
6,0.001086+0.421474j,0.001117+0.417618j,0.000613+0.399061j,0.001228+0.414592j,0.001861+0.393491j,0.002207+0.370177j,0.001641+0.410457j,0.002386+0.360275j,0.002733+0.312767j,0.002815+0.304171j,...,-0.034230+0.860190j,-0.038172+1.014707j,-0.051314+1.288331j,-0.061759+1.539459j,-0.080929+1.914210j,-0.096361+2.257549j,-0.116800+2.686190j,-0.140379+3.182426j,0.161094-1.150934j,0.164679-1.306247j
7,0.001759+0.226044j,0.001796+0.218232j,0.001479+0.274745j,0.001918+0.218335j,0.002220+0.107152j,0.002354+0.036523j,0.002241+0.173820j,0.002423+0.030489j,0.002444-0.067663j,0.002452-0.073248j,...,0.056405+0.181724j,0.060453+0.203313j,0.062987+0.268507j,0.065846+0.323704j,0.067562+0.418372j,0.069587+0.496872j,0.070935+0.597445j,0.071991+0.711829j,0.021025-0.420533j,0.017820-0.449229j
8,0.001774+0.008115j,0.001806-0.000299j,0.001796+0.105349j,0.001886+0.002318j,0.001714-0.149491j,0.001556-0.234893j,0.001983-0.063666j,0.001483-0.234006j,0.001146-0.333905j,0.001081-0.333203j,...,0.025389-0.012716j,0.026211-0.005904j,0.027635+0.009380j,0.028765+0.019368j,0.030547+0.034702j,0.032046+0.044414j,0.034017+0.055793j,0.036476+0.067129j,-0.023864-0.054226j,-0.024995-0.052306j
9,0.001257-0.169188j,0.001277-0.174362j,0.001596-0.055546j,0.001290-0.169888j,0.000684-0.304525j,0.000280-0.369139j,0.001120-0.232978j,0.000104-0.360702j,-0.000458-0.417284j,-0.000561-0.411157j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
10,0.000438-0.269636j,0.000447-0.269565j,0.001018-0.174280j,0.000389-0.265189j,-0.000456-0.335162j,-0.000962-0.352390j,0.000008-0.304004j,-0.001157-0.339586j,-0.001700-0.324617j,-0.001786-0.315357j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
11,-0.000421-0.282741j,-0.000422-0.278864j,0.000253-0.233913j,-0.000526-0.274680j,-0.001328-0.254004j,-0.001735-0.211803j,-0.000991-0.275481j,-0.001863-0.200787j,-0.002137-0.115668j,-0.002160-0.107015j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
12,-0.001089-0.218941j,-0.001095-0.211559j,-0.000499-0.232071j,-0.001210-0.209232j,-0.001688-0.099946j,-0.001821-0.009605j,-0.001600-0.169171j,-0.001815-0.003558j,-0.001661+0.124036j,-0.001607+0.126394j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
13,-0.001405-0.102228j,-0.001416-0.094039j,-0.001070-0.177629j,-0.001501-0.094026j,-0.001458+0.075400j,-0.001222+0.186051j,-0.001675-0.022393j,-0.001080+0.181445j,-0.000511+0.299969j,-0.000405+0.294217j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
14,-0.001310+0.034838j,-0.001325+0.040518j,-0.001348-0.087413j,-0.001350+0.038399j,-0.000751+0.215151j,-0.000196+0.301653j,-0.001228+0.122001j,0.000030+0.288556j,0.000784+0.336618j,0.000887+0.324779j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
15,-0.000848+0.155335j,-0.000870+0.156546j,-0.001288+0.016567j,-0.000821+0.152876j,0.000172+0.273833j,0.000835+0.288806j,-0.000420+0.221655j,0.001046+0.273127j,0.001582+0.202060j,0.001625+0.191600j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
16,-0.000165+0.226806j,-0.000194+0.223208j,-0.000923+0.111380j,-0.000082+0.218635j,0.000960+0.224834j,0.001405+0.138951j,0.000473+0.244697j,0.001484+0.127843j,0.001390-0.063238j,0.001337-0.065181j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
17,0.000527+0.225964j,0.000497+0.218762j,-0.000352+0.175501j,0.000635+0.214605j,0.001275+0.074270j,0.001183-0.103064j,0.001131+0.177511j,0.001055-0.101011j,0.000203-0.325913j,0.000075-0.314969j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
18,0.000994+0.146350j,0.000975+0.138200j,0.000276+0.192940j,0.001082+0.135812j,0.000925-0.129598j,0.000203-0.316499j,0.001276+0.032418j,-0.000096-0.298509j,-0.001080-0.333165j,-0.001180-0.317264j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
19,0.001047+0.003211j,0.001052-0.001865j,0.000789+0.156039j,0.001074-0.001209j,0.000031-0.285589j,-0.000847-0.288998j,0.000795-0.143816j,-0.001089-0.268364j,-0.000165+0.309742j,-0.000040+0.297538j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
20,0.000618-0.158496j,0.000662-0.157067j,0.001027+0.069016j,0.000565-0.153117j,-0.000795-0.229804j,-0.000303+0.300567j,-0.000133-0.264321j,0.000008+0.281618j,0.000000+0.000000j,0.000000+0.000000j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
21,-0.000132-0.258709j,-0.000057-0.250378j,0.000893-0.048906j,-0.000244-0.244528j,-0.000232+0.272568j,0.000000+0.000000j,-0.000868-0.193435j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
22,-0.000712-0.175938j,-0.000657-0.167000j,0.000398-0.161189j,-0.000798-0.163143j,0.000000+0.000000j,0.000000+0.000000j,-0.000158+0.257392j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
23,-0.000170+0.258140j,-0.000270+0.250223j,-0.000271-0.210587j,-0.000067+0.243903j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
24,0.000000+0.000000j,0.000000+0.000000j,-0.000692-0.117000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j
25,0.000000+0.000000j,0.000000+0.000000j,-0.000136+0.224614j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,...,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j,0.000000+0.000000j

In [20]:
# export as csv 
df_processed.to_csv("cochba_py_processed.csv", index=False, header=False)